export const projects = [
  {
    name: "Amazon website clone",
    image: "./images/amazon.png",
    desc: "A clone of the amazon website including login, cart and checkout functionality",
    live_url: "https://clone-project-be7d1.web.app/",
    code_url: "https://github.com/Michelle031/amazon-clone.git",
    tools: ["CSS", "JavaScript", "React", "React Context API", "Firebase"],
  },
  {
    name: "EasyBank Landing Page",
    image: "./images/desktop-design.jpg",
    desc: "Next generation digital banking",
    live_url: "https://michelle031.github.io/easybank-website/",
    code_url: "https://github.com/Michelle031/easybank-website.git",
    tools: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "Google clone",
    image: "./images/google.png",
    desc: "A clone of the google search engine using Google API ",
    live_url: "https://next-google-clone-snowy.vercel.app/",
    code_url: "https://github.com/Michelle031/next-google-clone",
    tools: ["TailWindCSS", "JavaScript", "React", "NextJs"],
  },
  {
    name: "Remotive/Github Jobs Board",
    image: "./images/dev8.png",
    desc: "You can filter the jobs by location, title and skills, learn more about it and also apply by clicking on it.",
    live_url: "https://quiet-gumdrop-cec8d9.netlify.app/",
    code_url: "https://github.com/Michelle031/github-remotive--jobs",
    tools: ["TailWindCSS", "JavaScript", "React", "Redux", "Pagination"],
  },
  {
    name: "Hulu clone",
    image: "./images/hulu.jpg",
    desc: "A clone of the hulu website using TMDB API ",
    live_url: "https://next-hulu-clone-two.vercel.app/",
    code_url: "https://github.com/Michelle031/next-hulu-clone",
    tools: ["TailWindCSS", "JavaScript", "React", "NextJs"],
  },
  {
    name: "Instagram clone",
    image: "./images/instagram.png",
    desc: "An instagram clone with some of the functionalities",
    live_url: "https://nextjs-insta-clone.vercel.app/",
    code_url: "https://github.com/Michelle031/nextjs-insta-clone.git",
    tools: ["TailWindCSS", "JavaScript", "React", "NextJs"],
  },
  {
    name: "Medium clone",
    image: "./images/medium.jpg",
    desc: "The medium blog clone",
    live_url: "https://sanity-medium-build-psi.vercel.app/",
    code_url: "https://github.com/Michelle031/sanity-medium-build.git",
    tools: [
      "TailWindCSS",
      "JavaScript",
      "React",
      "TypeScript",
      "NextJs",
      "Sanity",
    ],
  },
  {
    name: "Microsoft Landing Page clone",
    image: "./images/microsoft.png",
    desc: "The microsoft landing page clone",
    live_url: "https://michelle031.github.io/microsoft-clone/",
    code_url: "https://github.com/Michelle031/microsoft-clone.git",
    tools: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "Portfolio Website",
    image: "./images/portfolio.png",
    desc: "My Portfolio Website",
    live_url: "https://michelleanne-portofolio.web.app",
    code_url: "https://github.com/Michelle031/portfolio-app.git",
    tools: ["CSS", "JavaScript", "React"],
  },
  {
    name: "Rest Countries Quiz App",
    image: "./images/dev6.png",
    desc: "Questions about countries based on their flag or capital",
    live_url: "https://shiny-brigadeiros-eec32b.netlify.app/",
    code_url: "https://github.com/Michelle031/country-quiz",
    tools: ["TailwindCSS", "React", "API", "Redux", "lodash"],
  },
  {
    name: "React calculator app",
    image: "./images/desktop-design-theme-1.jpg",
    desc: "Math has never been so easy and interactive",
    live_url: "https://michelle031.github.io/react-calculator/",
    code_url: "https://github.com/Michelle031/react-calculator.git",
    tools: ["CSS", "JavaScript", "React"],
  },
  {
    name: "React todolist",
    image: "./images/desktop-design-dark.jpg",
    desc: "Plan and outline your tasks better",
    live_url: "https://michelle031.github.io/todolist-react/",
    code_url: "https://github.com/Michelle031/todolist-react.git",
    tools: ["CSS", "JavaScript", "React"],
  },
  {
    name: "Rest Countries API Website",
    image: "./images/desktop-design-home-light.jpg",
    desc: "Information about countries at the click of a button",
    live_url: "https://michelle031.github.io/test-rest-countries-project/",
    code_url: "https://github.com/Michelle031/test-rest-countries-project.git",
    tools: ["CSS", "JavaScript", "React", "API"],
  },
  {
    name: "Rock Paper Scissors",
    image: "./images/desktop-step-1.jpg",
    desc: "A colorful build of the good old rock paper scissors game",
    live_url: "https://michelle031.github.io/rock-paper-scissors/",
    code_url: "https://github.com/Michelle031/rock-paper-scissors.git",
    tools: ["HTML", "CSS", "JavaScript"],
  },
  {
    name: "Shortening URL Website",
    image: "./images/desktop-design_2.jpg",
    desc: "Shorten those links!",
    live_url: "https://michelle031.github.io/url-shortener-project/",
    code_url: "https://github.com/Michelle031/url-shortener-project.git",
    tools: ["HTML", "CSS", "JavaScript", "API"],
  },
  {
    name: "Social Media Dashboard",
    image: "./images/active-states-dark.jpg",
    desc: "Keep track of your social media accounts",
    live_url: "https://michelle031.github.io/social-media-dashboard/",
    code_url: "https://github.com/Michelle031/social-media-dashboard.git",
    tools: ["HTML", "CSS", "Sass", "JavaScript"],
  },
  {
    name: "Tetris Game",
    image: "./images/1138720.png",
    desc: "Let's play tetris",
    live_url: "https://michelle031.github.io/tetris-game/",
    code_url: "https://github.com/Michelle031/tetris-game.git",
    tools: ["HTML", "CSS", "JavaScript"],
  },
];
